FROM clojure

# user-wide profiles
COPY docker/user_profile/ /root/.lein/

# project
RUN mkdir -p /tmp/app 
COPY project.clj /tmp/app

# pull and cache the deps
WORKDIR /tmp/app
RUN lein deps

# ring web server
EXPOSE 3000

# nrepl 
EXPOSE 7888

# figwheel nrepl
EXPOSE 3449

# start ring embedded server
CMD lein trampoline repl :headless :host 0.0.0.0 :port 7888