FROM clojure

# Project directory
VOLUME /webapp
WORKDIR /webapp

# Ports publish (web server, nrepl server, figwheel repl server)
EXPOSE 8080 7888 3449

CMD lein trampoline repl :headless :host 0.0.0.0 :port 7888